### ISSUE TITLE
DllNotFoundException Dicom.Native for docker net core application

### ISSUE THREAD

**Issue by sylvainb31** [Efferent-Health/fo-dicom.Codecs#79] opened 2024-07-24 08:58 UTC
Hello,

I have opened an issue on the fo-dicom github but as it is related to the native codecs, I am opening it here as well :

https://github.com/fo-dicom/fo-dicom/issues/1826

Steps to dockerise my application :

```
dotnet publish –c Release

docker build –t imageToBuild –f Dockerfile .
```

Here is the content of my DockerFile :

FROM mcr.microsoft.com/dotnet/aspnet:5.0
RUN apt-get update
RUN apt-get install -y libgdiplus libc6-dev
RUN apt-get install -y libicu-dev libharfbuzz0b libfontconfig1 libfreetype6
ENV TZ=Europe/Paris
ENV LANG fr_FR.UTF-8
ENV LANGUAGE ${LANG}
ENV LC_ALL ${LANG}
COPY ./bin/Release/net5.0/publish/ App/
WORKDIR /App
ENTRYPOINT ["dotnet", "App.dll"]

Am I missing something ? Maybe when publishing my app ?

Thanks for your help,

**Comment by jaime-olivares** [comment] 2024-08-01 15:56
This is not a bug at all, but a docker misconfiguration problem.

**Comment by jaime-olivares** [comment] 2024-08-05 20:05
Well, we are closing this one as it is not a library issue. We use docker in a regular basis.
Our suggestion is to use .NET 6.0 at least (prefer 8.0), and last versions of fo-dicom v5 and fo-dicom.Codecs.

**Closed by jaime-olivares** 2024-08-05 20:05 UTC
Labels: question
